### ISSUE TITLE
Refactor setup.py (remove test setup, and the like)

### ISSUE THREAD

**Issue by skulegirl** [jazzband/django-analytical#117] opened 2017-10-21 16:46 UTC
Installed from master today and ran into this error:

`django.core.exceptions.ImproperlyConfigured: Error loading either pysqlite2 or sqlite3 modules (tried in that order): No module named '_sqlite3'`

2.3.0 release doesn't seem to have this issue. Looks like commit 347df54502d4a921ff95aa0674712cdbd5c8fbf9 broke the setup.cfg.

Full text of error:
```
> pip install git+https://github.com/jcassee/django-analytical.git
Collecting git+https://github.com/jcassee/django-analytical.git
  Cloning https://github.com/jcassee/django-analytical.git to /tmp/pip-vtw00h9e-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/webapps/bdw3_20171021121342Z/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 31, in <module>
        from pysqlite2 import dbapi2 as Database
    ModuleNotFoundError: No module named 'pysqlite2'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/webapps/bdw3_20171021121342Z/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 33, in <module>
        from sqlite3 import dbapi2 as Database
      File "/usr/local/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
        from sqlite3.dbapi2 import *
      File "/usr/local/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
        from _sqlite3 import *
    ModuleNotFoundError: No module named '_sqlite3'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-vtw00h9e-build/setup.py", line 49, in <module>
        django.setup()
      File "/webapps/bdw3_20171021121342Z/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
        apps.populate(settings.INSTALLED_APPS)
      File "/webapps/bdw3_20171021121342Z/lib/python3.6/site-packages/django/apps/registry.py", line 108, in populate
        app_config.import_models()
      File "/webapps/bdw3_20171021121342Z/lib/python3.6/site-packages/django/apps/config.py", line 202, in import_models
        self.models_module = import_module(models_module_name)
      File "/webapps/bdw3_20171021121342Z/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 978, in _gcd_import
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
      File "/webapps/bdw3_20171021121342Z/lib/python3.6/site-packages/django/contrib/auth/models.py", line 4, in <module>
        from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
      File "/webapps/bdw3_20171021121342Z/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 52, in <module>
        class AbstractBaseUser(models.Model):
      File "/webapps/bdw3_20171021121342Z/lib/python3.6/site-packages/django/db/models/base.py", line 124, in __new__
        new_class.add_to_class('_meta', Options(meta, app_label))
      File "/webapps/bdw3_20171021121342Z/lib/python3.6/site-packages/django/db/models/base.py", line 325, in add_to_class
        value.contribute_to_class(cls, name)
      File "/webapps/bdw3_20171021121342Z/lib/python3.6/site-packages/django/db/models/options.py", line 214, in contribute_to_class
        self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
      File "/webapps/bdw3_20171021121342Z/lib/python3.6/site-packages/django/db/__init__.py", line 33, in __getattr__
        return getattr(connections[DEFAULT_DB_ALIAS], item)
      File "/webapps/bdw3_20171021121342Z/lib/python3.6/site-packages/django/db/utils.py", line 211, in __getitem__
        backend = load_backend(db['ENGINE'])
      File "/webapps/bdw3_20171021121342Z/lib/python3.6/site-packages/django/db/utils.py", line 115, in load_backend
        return import_module('%s.base' % backend_name)
      File "/webapps/bdw3_20171021121342Z/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "/webapps/bdw3_20171021121342Z/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 35, in <module>
        raise ImproperlyConfigured("Error loading either pysqlite2 or sqlite3 modules (tried in that order): %s" % exc)
    django.core.exceptions.ImproperlyConfigured: Error loading either pysqlite2 or sqlite3 modules (tried in that order): No module named '_sqlite3'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-vtw00h9e-build/
```

**Comment by skulegirl** [comment] 2017-10-21 16:52
Correction: Installing from pypi works fine, but installing from source fails, even before 2.3.0 release. So it's not that commit, but something else.

**Comment by goabout-tech** [comment] 2017-10-21 18:58
Not sure, but the stacktrace seems to indicate the problem is with the installation of Django?

**Comment by jcassee** [comment] 2017-10-21 18:59
Not sure, but the stacktrace seems to indicate the problem is with the installation of Django?

**Comment by skulegirl** [comment] 2017-10-21 22:40
Well, I don't have sqlite3 installed, but I shouldn't need it for this app. I did actually figure out the issue, the setup.py file tries to set the env to include the tests.settings automatically, which requires sqlite3. Remove the following from the setup.py file:

```
-try:
 -    import django
 -    os.environ.setdefault(
 -        "DJANGO_SETTINGS_MODULE",
 -        "analytical.tests.settings"
 -    )
 -    django.setup()
 -except ImportError:
 -    print(
 -        "Could not import django. "
 -        "This is fine, unless you intend to run unit tests."
 -    )
 -
```

**Comment by bittner** [comment] 2019-01-11 23:42
Thanks @skulegirl, for identifying the issue! :+1:  This translates to: We need to

1. refactor [setup.py](https://github.com/jazzband/django-analytical/blob/master/setup.py) reducing the logic for just packaging,
1. run tests "from outside" (and without) setup.py, e.g. using pytest,
1. optionally, move the tests out of the [analytical module](https://github.com/jazzband/django-analytical/tree/master/analytical) and make sure they're not included when the package is build to PyPI.

**Comment by bittner** [comment] 2020-11-30 22:07
@skulegirl PR #171 removed the code [you objected about](https://github.com/jazzband/django-analytical/issues/117#issuecomment-338437270), reducing the overall complexity of our `setup.py`.

Hence, it's very likely that your issue is now fixed. Please, let us know if this is not the case.

**Closed by bittner** 2020-11-30 22:07 UTC
Labels: bug, help-wanted
